services: 
  mysql: 
    image: mysql:8.0-debian
    volumes: 
      - planner-web-app-mysql-data:/var/lib/mysql
    ports: 
      - "8000:3306"
    env_file:
      - .env
    
  api: 
    image: planner-web-app
    depends_on:
      - mysql
    build: 
      context: ./Backend
      target: development
      dockerfile: API/Dockerfile
    ports: 
      - "8001:8080"
      - "8002:8081"
    env_file:
      - .env
    volumes: 
      - ./Backend:/app


volumes: 
  planner-web-app-mysql-data:

