services: 
  api: 
    build: 
      context: ./Backend
      target: development
      dockerfile: API/Dockerfile
    ports: 
      - "8001:8001"
      - "8002:8002"
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes: 
      - ./Backend:/app/Backend/



