services: 
  mysql: 
    image: mysql:8.0-debian
    volumes: 
      - planner-web-app-mysql-data:/var/lib/mysql
    ports: 
      - "8000:3306"
    env_file:
      - .env

volumes: 
  planner-web-app-mysql-data:

